<a href="https://colab.research.google.com/github/Kengo-Akechi/ML-Projects/blob/main/Diabetes_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# splitting the dataset into: train- test
from sklearn.model_selection import train_test_split

# checking model accuracy
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix # to evaluate model

In [ ]:
data=pd.read_csv('diabetes.csv')
print(data.isnull().any())

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool


In [ ]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
x = data.drop(columns=['Outcome'])
y = data['Outcome']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
Y_train.head()

206    1
96     0
128    1
460    0
275    0
Name: Outcome, dtype: int64

In [ ]:
# importing the model generator
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
# training the model
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [ ]:
# prediction using test set
y_pred = model.predict(X_test)

In [ ]:
# Evaluation
model.score(X_test,Y_test)

0.8246753246753247

In [ ]:
# Evaluation using Classification Report
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_pred,Y_test))

              precision    recall  f1-score   support

           0       0.93      0.83      0.88       117
           1       0.60      0.81      0.69        37

    accuracy                           0.82       154
   macro avg       0.77      0.82      0.78       154
weighted avg       0.85      0.82      0.83       154



In [ ]:
conf_mat=confusion_matrix(Y_test,y_pred)
conf_mat

array([[97,  7],
       [20, 30]], dtype=int64)

In [ ]:
#----------------------------------------------------------------------------------------------------------------------------

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf= DecisionTreeClassifier()

In [ ]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier()

In [ ]:
clf.predict(X_test)

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [ ]:
clf.score(X_test,Y_test)

0.7012987012987013

In [ ]:
print(classification_report(y_pred,Y_test))

              precision    recall  f1-score   support

           0       0.93      0.83      0.88       117
           1       0.60      0.81      0.69        37

    accuracy                           0.82       154
   macro avg       0.77      0.82      0.78       154
weighted avg       0.85      0.82      0.83       154



In [ ]:
conf_mat=confusion_matrix(Y_test,y_pred)
conf_mat

array([[97,  7],
       [20, 30]], dtype=int64)

In [ ]:
#------------------------------------------------------------------------------------------------------------------------------

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train, Y_train)

RandomForestClassifier()

In [ ]:
rf.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [ ]:
rf.score(X_test,Y_test)

0.8441558441558441

In [ ]:
#-----------------------------------------------------------------------------------------------------------

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
knn.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [ ]:
knn.score(X_test,Y_test)

0.7272727272727273